spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attribute
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8050
services:
  company-url: http://kinomino.ru:8060/api/company
  warehouse-url: http://kinomino.ru:8080/api/company